### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by coolprobn** [TommyJ1994/keyonic-v2#3]
I am getting following error after successful login, what could be the issue?

<img width="631" alt="screen shot 2018-02-16 at 1 11 54 am" src="https://user-images.githubusercontent.com/15196941/36276568-7ff990d4-12b6-11e8-834f-b21c04772c4e.png">

**Comment by coolprobn** [comment]
It was my mistake, I imported users in realm I already had and thought this would work.
It was solved when I also imported realm as suggested in documentation.

**Comment by mluis** [comment]
I'm having the same issue. Would you mind referencing the documentation you're stating? Thanks
