### ISSUE TITLE
User details when social login

### ISSUE THREAD

**Issue by magick93** [TommyJ1994/keyonic-v2#4]
Hello

When I login with a normal user (that is, with username and password) I can see the users details in the app. But if I try using a social login, such as Facebook, I cannot see the users details in the app - even though these details are visible in Keycloak.

Any ideas as to what I am doing wrong?

Thanks

**Comment by tomjackman** [comment]
@magick93 The user details are for Keycloak users only - this is a Keycloak feature, not an OpenID Connect one. When you use social logins, you are using OpenID Connect for Facebook. You will need to fetch the users details from Facebook manually.

**Comment by magick93** [comment]
Hi @TommyJ1994 

Why would I need to fetch them from Facebook when they are already stored in Keycloak? 

From Keycloaks perspective Facebook is an Identity Provider, and when logging in using FB, Keycloak stores the basic user info into the same user data model that is used for 'normal' keycloak users. So I cant understand why you recommend to fetch details manually from Facebook.

**Comment by tomjackman** [comment]
@magick93 Keycloak user attributes like job, avatar etc that I added for this demo are not an OpenID Connect feature, its a Keycloak feature. OpenID Connect only defined ones like email, username, first name, last name as part of the protocol. The extra user attributes are a Keycloak feature. So when you use OpenID Connect identity brokering to login to Facebook, you are retrieving the user info from Facebook, not from Keycloak's user store (which has the extra information).

If you link the Keycloak account to a Facebook account inside of Keycloak (i think there is an option in the social login config) then this might work for you. But this is a Keycloak issue, not this sample app - as Keycloak doesn't pass down the user attributes for social logins. Make sense?

**Comment by magick93** [comment]
I found a fix - perhaps not the ideal fix.

By adding the `avatar` attribute, and giving it a value, to a user that originated from Facebook (and presumably any other social login) I was able to view the user info in the app.

![screenshot from 2018-02-16 21-18-50](https://user-images.githubusercontent.com/2173213/36303326-a2db2d6e-1370-11e8-96ff-e19092dd3b65.png)
